<?php

    include('data.php');



    /* Function to call the API */

            /* previous version https://weichie.com/blog/curl-api-calls-with-php/ */

    // Code generated by Insomnia */

    function callAPI($url, $APIKEY){

        $curl = curl_init();

        curl_setopt_array($curl, [
            CURLOPT_CAINFO => __DIR__ . DIRECTORY_SEPARATOR . 'cacert-2021-09-30.pem' , // https://curl.se/docs/caextract.html
            CURLOPT_PORT => "443",
            CURLOPT_URL => $url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "GET",
            CURLOPT_POSTFIELDS => "",
            CURLOPT_HTTPHEADER => [
                //"ApiKey: xxx",
                $APIKEY,
                "Authorization: Basic Og=="
            ],
        ]);

        $response = curl_exec($curl);
        $err = curl_error($curl);

        curl_close($curl);

        if ($err) {
        echo "cURL Error #:" . $err;
        } else {
        echo $response;
        }

    }
    
    /* Get today's date */
  
    $date = date_create();
    if (!$date) {
        $e = date_get_last_errors();
        foreach ($e['errors'] as $error) {
            echo "$error\n";
        }
        exit(1);
    }
    
    $currentDate = date_format($date, 'Y-m-d');

    
    $hashedCurrentDate = crc32($currentDate); // hash the date 

  
    $dividedHashedDate = $hashedCurrentDate / 4294967295 /*  2147483647 */; // divide the hash by the maximum number of a 32bit integer number


    // Get the index position from the hash number * the length of the id's lists
    $indexPositionPainting = abs(round($dividedHashedDate * count($idListPaintings))); 
    $indexPositionSculpture = abs(round($dividedHashedDate * count($idListSculptures)));
    $indexPositionPhotograph = abs(round($dividedHashedDate * count($idListPhotographs)));

    // The index position gives the artwork of today, and we need to get its ID so we can fetch the corresponding data and send it back to our JS code.
    $idPaintingOfTheDay = $idListPaintings[$indexPositionPainting];
    $idSculptureOfTheDay = $idListSculptures[$indexPositionSculpture];
    $idPhotographOfTheDay = $idListPhotographs[$indexPositionPhotograph];

 
    

   
?>